hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://nuplan.planning.script.config.common
    - pkg://nuplan.planning.script.experiments      # Put experiments configs in script/experiments/<exp_dir>

model_name: ???
output_dir: ???
dataset: ???

# Hyperparameters see QLoRa https://arxiv.org/pdf/2305.14314.pdf
lora_config:
  _target_: peft.LoraConfig
  _convert_ : "all"
  lora_alpha: 16
  lora_dropout: 0.1
  r: 64
  bias: "none"
  task_type: "CAUSAL_LM"

training_arguments:
  _target_: transformers.TrainingArguments
  _convert_ : "all"
  output_dir: "${output_dir}/results"
  num_train_epochs: 1
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 1
  optim: "paged_adamw_32bit"  
  save_steps: 25
  logging_steps: 25
  learning_rate: 2e-4
  weight_decay: 0.001
  fp16: False
  bf16: False
  max_grad_norm: 0.3
  max_steps: -1
  warmup_ratio: 0.03
  group_by_length: True
  lr_scheduler_type: "constant"
  report_to: "tensorboard"